version: '3'
services:
    core_api:
        build: .
        command: uvicorn main:app --host 0.0.0.0 --port $PORT
        ports:
            - "8080:8080"
        volumes:
            - ./app/:/app
